complete-dbt-bootcamp-zero-to-hero:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: '1234'
      port: 5432
      dbname: postgres # or database instead of dbname
      schema: public